// const html = `<!DOCTYPE html>
// <body>
//   <h1>Hello World</h1>
//   <p>This markup was generated by a Cloudflare Worker.</p>
// </body>`;

// const worker: ExportedHandler = {
// 	async fetch(req) {
// 		return new Response(html, {
// 			headers: {
// 				'content-type': 'text/html;charset=UTF-8',
// 			},
// 		});
// 	},
// };

// export default worker;
